name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v4
        with:
          node-version: "21.x"

      - name: Install Dependencies
        run: bun install

      - name: Build TypeScript
        run: npm run build
      
      - name: Run Tests
        run: bun test
